compressionLevel: mixed

enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"

pnpIgnorePatterns:
  - ./nm-packages/**

yarnPath: .yarn/releases/yarn-4.5.0.cjs
