[package]
name = "engine_swc_plugin_syntax"
version = "1.0.0"
edition = "2021"
authors = ["Code11 Team"]
description = "SWC plugin for processing engine type annotations"
license = "MIT"
repository = "https://github.com/code11/engine"
documentation = "https://github.com/code11/engine/tree/main/packages/engine.swc-plugin-syntax#readme"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
swc_core = { version = "0.90", features = ["plugin_transform"] }
swc_ecma_ast = "0.112"
swc_ecma_parser = "0.141"
swc_ecma_visit = "0.98"
swc_common = { version = "0.33", features = ["tty-emitter"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
testing = "0.35.6"
tempfile = "3.8"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1